GET http://localhost:5000/categories

###
GET http://localhost:5000/categories/5f1958253a9bd83aa87b4564

###
POST http://localhost:5000/categories
Content-Type: application/json

{
    "name": "Laptop"
}

###
PATCH http://localhost:5000/categories/5f1958253a9bd83aa87b4564
Content-Type: application/json

{
    "name": "sfgfs"
}

###
DELETE http://localhost:5000/categories/5f1c6ef0d13fb216b0d8cf9b



###
GET http://localhost:5000/products

###
GET http://localhost:5000/products/5f195223c2f0cc2f3a46eed1

###
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "OnePlus",
    "category": "Mobile",
    "purchasePrice": 10000,
    "sellPrice": 15000
}

###
PATCH http://localhost:5000/products/5f1c70e2a43b8f187fa8e827
Content-Type: application/json

{
    "name": "Mac"
}

###
DELETE http://localhost:5000/products/5f195223c2f0cc2f3a46eed1